name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_esp32:

    name: build esp32

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              version: 2.0.13
          sketch-paths: |
            - ./
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/marcel-licence/ML_SynthTools_Lib.git
                name: ML_SynthTools_Lib
              - source-url: 
                name: Adafruit_NeoPixel
                version: 1.12.2
